// Navigation
export const NAVIGATION_GO_TO_PAGE = 'NAVIGATION_GO_TO_PAGE'
export const NAVIGATION_BACKWARD = 'NAVIGATION_BACKWARD'

// Restaurant
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT'
export const DESELECT_RESTAURANT = 'DESELECT_RESTAURANT'

export const SELECT_MENU = 'SELECT_MENU'
export const DESELECT_MENU = 'DESELECT_MENU'

export const SELECT_PIATTO = 'SELECT_PIATTO'
export const DESELECT_PIATTO = 'DESELECT_PIATTO'

export const SET_FETCHED_RESTAURANT = 'SET_FETCHED_RESTAURANT'
export const SET_FETCHED_BOOKING = 'SET_FETCHED_BOOKING'


//Counter
export const COUNTER_RESET = 'RESET';
export const COUNTER_INCREMENT = 'INCREMENT';
export const COUNTER_DECREMENT = 'DECREMENT';

//variableMenu
export const VMENU_ADD_EL = 'VMENU_ADD_EL'
export const VMENU_REMOVE_EL = 'VMENU_REMOVE_EL'
export const VMENU_ADD_NAME_INDEX = 'VMENU_ADD_NAME_INDEX'
export const VMENU_RESET = 'VMENU_RESET'
export const VMENU_ADD_MENU= 'VMENU_ADD_MENU'


//Reservation
export const RESERVATION_SET_FIXED_INFO = 'RESERVATION_SET_FIXED_INFO'
export const RESERVATION_SET_VARIABLE_INFO = 'RESERVATION_SET_VARIABLE_INFO'
export const RESERVATION_SET_SINGLE_VMENU = 'RESERVATION_SET_SINGLE_VMENU'
export const RESERVATION_RESET = 'RESERVATION_RESET'
